name: Generate USAllParts YML

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sheets-updated]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml

      - name: Generate YML
        env:
          PYTHONIOENCODING: utf-8
        run: |
          python yml_build.py
          test -f USAllParts.yml

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add USAllParts.yml
          git commit -m "chore: auto-generate USAllParts.yml" || echo "No changes to commit"
          git push


